### ISSUE TITLE
Caching the values

### ISSUE THREAD

**Issue by adam-r-kowalski** [coreytrampe/elm-vendor#2]
I am using this library quite extensively in my library [Elm-Css](https://github.com/adam-r-kowalski/Elm-Css/), and I just wanted to say thanks for making it possible!

I do have one question however, and it deals with performance. Given that I am calling this often should I expect a performance hit or is safe to use repeatedly? Would it make sense to cache the value and only perform calculations if no value is cached, and otherwise return the saved result?

**Comment by coreytrampe** [comment]
It's only calling getComputedStyles once, and that's the expensive thing. I'd be really surprised if the time spent inside Vendor.prefix mattered.

Let me know if you observe otherwise!

**Comment by coreytrampe** [comment]
( We are comparing string in there... but they're probably interned, so really just comparing pointers... )
